#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <iostream>
#include <fstream>
#include <string>
#include <thread>
#include <vector>
#include <unordered_map>
#include "include/Python.h"
#include "BDS.hpp"
//#include "head/ArduinoJson.h"
